name: Replace & Deploy to EC2

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_EC2_SSH: ${{ secrets.EC2_SSH }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init and Apply
        id: terraform_init
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve
          # terraform apply -auto-approve -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" 
          echo "::set-output name=ec2_instance_ip::$(terraform output ec2_instance_ip)"
      - name: Copy ML_API to EC2  
        uses: appleboy/scp-action@master
        with:
          host: ${{ steps.terraform_init.outputs.ec2_instance_ip }}
          username: ${{ secrets.EC2_USER }}
          port: 22
          key: ${{secrets.EC2_PRIVATE_SSH}}
          source: "ML_API/*"
          target: "/opt/ML_API"
          

