name: Replace & Deploy to EC2

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init and Apply
        id: terraform_init
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      - name: Copy ML_API to EC2
        id: ec2_ip
        run: |
          # cd terraform
          echo "copying ${{steps.terraform_init.outputs.ec2_instance_ip}} to ec2..."
          echo "${{steps.terraform_init.outputs.ec2_instance_ip}}"
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Copy ML_API to EC2  
        uses: appleboy/scp-action@master
        with:
          host: ${{ steps.terraform_init.outputs.ec2_instance_ip }}
          username: ${{ secrets.EC2_USER }}
          port: ${{ steps.terraform_init.outputs.public_dns }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: "ML_API/*"
          target: ":/"
          

