name: Replace & Deploy to EC2

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
      - name: Terraform Init and Apply
        id: terraform_init
        run: |
          cd terraform
          terraform init
          terraform apply -auto-approve -var="AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

          echo "try this 2"
          echo "instance_ip=$(terraform output ec2_instance_ip) >> $GITHUB_ENV"
          echo "this 3"
          echo "${{env}}"

          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # - name: Copy ML_API to EC2
      #   id: ec2_ip
      #   run: |
      #     # cd terraform
      #     echo "testing..."
      #     echo "${{steps.terraform_init.outputs.ec2_instance_ip}}"
      #     # cd ML_API
      #     # scp -o StrictHostKeyChecking=no -r . ec2-user@${{ steps.terraform_init.outputs.ec2_instance_ip }}:/
      #   env:
      #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
